Test Report - 2025-04-04_16-19-26
==================================================

Total Tests Run: 15
Successful: 13
Failed: 2
Errors: 0
Run Time: 0:00:00.223102

Failed Tests:
--------------------
test_file_too_large (test_app.TestImageResizerApp.test_file_too_large)
Traceback (most recent call last):
  File "/Users/ganeshbollem/Documents/image-resizer-app/tests/test_app.py", line 121, in test_file_too_large
    self.assertEqual(json_data['error'], 'File size exceeds limit')
AssertionError: 'Total file size exceeds limit' != 'File size exceeds limit'
- Total file size exceeds limit
? ^^^^^^^
+ File size exceeds limit
? ^



test_convert_to_pdf_file_too_large (test_pdf.TestPDFConversion.test_convert_to_pdf_file_too_large)
Traceback (most recent call last):
  File "/Users/ganeshbollem/Documents/image-resizer-app/tests/test_pdf.py", line 76, in test_convert_to_pdf_file_too_large
    self.assertEqual(json_data['error'], 'Individual file size exceeds limit')
AssertionError: 'Total file size exceeds limit' != 'Individual file size exceeds limit'
- Total file size exceeds limit
? ^^^
+ Individual file size exceeds limit
? ^^^^^^^^



